server:
  port: 8081
  servlet:
    context-path: /api

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: gonglian-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wallte?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  data:
    redis:
      host: 47.122.24.43
      port: 6379
      database: 0
      password: 200152
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: 8677df7fc3a34e26a61c034d5ec8245d
  expiration: 86400000

logging:
  level:
    root: INFO
    com.gonglian: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.gonglian.controller
  show-actuator: false
